num1 = input("Nhập num1: ")
num2 = input("Nhập num2: ")
num1 = float(num1)
num2 = float(num2)
print(num1 + num2)
print(num1 - num2)
print(num1 * num2)
print(num1 / num2)
print(num1 // num2)
print(num1 % num2)
print(num1 ** num2)
